### ISSUE TITLE
Feature request: gracefully handle reply posting when "You're posting too fast. Please slow down. Thanks." is encountered

### ISSUE THREAD

**Issue by brandongalbraith** [plibither8/refined-hacker-news#107]
When posting a comment reply, if your Hacker News account is in the "penalty box" you might receive the error message ["You're posting too fast. Please slow down. Thanks."](https://github.com/minimaxir/hacker-news-undocumented/issues/21):

![Screen Shot 2021-10-06 at 1 37 55 PM](https://user-images.githubusercontent.com/350893/136255113-531d2f64-efaf-4f82-80de-cb80456bd45c.png)

Would it be possible to cache the reply comment locally for posting once the reply inhibit window has passed?

**Comment by G2G2G2G** [comment]
Yea via html5 local storage it's fairly straightforward

**Comment by jacalata** [comment]
They probably don't want to because you see this when dang has decided you're an ass, and your comment probably isn't worth having anyway.
