### ISSUE TITLE
[Feature] Upload images/videos

### ISSUE THREAD

**Issue by lookfirst** [plibither8/refined-hacker-news#120]
I know, HN doesn't support this, but bear with me for a moment.

What if, this extension abused the formatting of comments to allow some special formatting that this extension would then be able to parse and render for us? Something like, say... allow markdown in comments. The extension would then parse each comment and render the markdown directly.

Then, someone could either link to a photo or upload it directly to a 3rd party service (like imgurl) and then we could finally have images render inline in comments.

This could make HN a lot more fun imho. The self moderating ability of HN would prevent people from say... nfsw links to images and such.

**Comment by plibither8** [comment]
Thanks for the detailed feature request!

I understand where you're coming from, and this is something that could be beneficial in the eyes of a significant set of users. However, I do foresee a large backlash for a feature like this. The sole motto of this extension was to keep the soul of HN (simplicity) sacrosanct, and somehow I feel _rendering_ markdown in comments seems to be a step away from that.

Secondly - and this is a much more optimistic/ambitious take - if the usage of this extension and feature grows over time, we might reach a state where a lot of comments are written in MD, under the assumption that they can and will be rendered. This seems like a bit unfair for the larger set of users _not_ using this extension, or those using HN on mobile.

I hope you can get my hesitations, but please do let me know if you have more opinions on this. For now, I'll backlog this one! Thanks again :))
