### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'href')

### ISSUE THREAD

**Issue by lookfirst** [plibither8/refined-hacker-news#122]
Sorry man, another NPE...

![2022-09-27 at 18 37 18](https://user-images.githubusercontent.com/85355/192608889-45e5ada9-2d1d-4149-a7bb-fdf78eb6f5e6.png)

**Comment by plibither8** [comment]
Oof, that's frustrating. Thanks for pointing it - I'll have a look at it tomorrow! :)

**Comment by plibither8** [comment]
Fixed in https://github.com/plibither8/refined-hacker-news/commit/86575a1b7e4ddefbc85daecd3fd2ac79b691e96b and uploaded to the extension stores. Updates should be out soon, thanks for the patience! :)
