### ISSUE TITLE
title fetch is broken

### ISSUE THREAD

**Issue by lookfirst** [plibither8/refined-hacker-news#127]
![2022-12-12 at 17 53 24](https://user-images.githubusercontent.com/85355/207118282-e1694e9a-542b-4d37-b9e5-c3860f0e6174.png)

**Comment by plibither8** [comment]
Thanks for pointing out. Will push a fix today, the new URL is at https://title.mihir.ch and uses Cloudflare Workers instead of Vercel now

**Comment by lookfirst** [comment]
smart... CF workers kick ass. i use them heavily in the #dayjob.

**Comment by plibither8** [comment]
Fixed in https://github.com/plibither8/refined-hacker-news/commit/006b7bc0bfcef8aa22da9872fb977e95fee344f5.
