### ISSUE TITLE
Refined Hacker News is disabled error message on Chrome - requesting new permissions

### ISSUE THREAD

**Issue by chi-feng** [plibither8/refined-hacker-news#128]
<img width="322" alt="image" src="https://user-images.githubusercontent.com/336681/208372056-3f2c000d-b2b7-4774-8243-5d43aa9177c2.png">

It's asking to read and change data on title.mihir.ch, and when I visited the page to check what is it about, it displays the error message:
```
Error: TypeError: Invalid URL string.
```

**Comment by chi-feng** [comment]
Nvm, I see it is related to this change

https://github.com/plibither8/refined-hacker-news/commit/bcadc17d5ff7d6dd205e9d145a8c361bb2710c07

**Comment by plibither8** [comment]
Yeah sorry for that! The latest update is available on Chrome Webstore now so you should be seeing it work soon :). Thanks!
