### ISSUE TITLE
Features should not cause layout flap as they load

### ISSUE THREAD

**Issue by chris-morgan** [plibither8/refined-hacker-news#25]
Just trying this now, and the fact that enhancements take time to load, but they modify the document layout, causing layout flap, makes it quite painful to use.

A couple that immediately stood out:

- `.__rhn__comment-indent` uses `border-right: 1px solid #ccc` which increases its width by one pixel, making the comment shift a pixel to the right (and consequently occasionally reflow the text as well). Use `box-shadow: inset -1px 0 #ccc` instead so that the border doesn’t affect the layout.

- “toggle all comments” causes a big vertical jump; maybe float it right on the “add comment” button or the `.subtext`, or disable it by default, or statically reserve the space in CSS that will be in the first contentful paint, and then be replaced by the actual button/link once it can be added.

There may be others. I’ve tried it for less than four minutes so far.

**Comment by chris-morgan** [comment]
Ugh, just reloaded the front page, and the layout flap there is *really* painful, my remarks on the “toggle all comments” button/link go triple for `.__rhn__options-bar`.

**Comment by plibither8** [comment]
Hi!

> Use box-shadow: inset -1px 0 #ccc instead 

Thanks very much for this suggestion. It'll be implemented in the next update (today itself).

> “toggle all comments” causes a big vertical jump

Floating the link to right of the "add comment" button will only be possible on those items that are not so old that one cannot reply on them. So it's not a _universal_ solution per se. Also, I believe that this "action" of toggling won't be appropriate to add as a link in the `.subtext`.

Of course, you can disable this feature on your end, but I disabling _any_ feature by default seems very iffy. Nevertheless, I'll leave this to be judged by popular opinion.

Also, browser extension cannot "reserve" space, as all the content scripts and CSS styles of the extension are loaded only after the ones of the main page.

> [...] `.__rhn__options-bar`

There seems to be know "better" way to do this. Any suggestions?

Thanks for taking your time to review this extension by the way! Cheers.

**Comment by cdtinney** [comment]
@plibither8 perhaps the options bar could be rendered in a "collapsed" mode by default to make it slightly less jarring.

**Comment by Ajedi32** [comment]
I think the main cause of this issue is that the features currently load in sequence rather than in parallel:

https://github.com/plibither8/refined-hacker-news/blob/a43ecc4525166fe8f95614a6733e2b2441e2300d/src/libs/initialise.js#L139-L142

This, combined with the fact that some features seem to require network operations to fully load, results in a significant delay between when the page loads, and when the features load.

Updating the initializer to load everything in parallel, and updating each feature to make its DOM updates as early as possible would resolve this issue.

**Comment by cdtinney** [comment]
@Ajedi32  good catch. Considering linting was disabled for the `await`, however, maybe it was intentional to add them in a specific order (i.e. the order of `featureList`)?

**Comment by nick-s-b** [comment]
![Screenshot from 2019-06-13 22-17-14](https://user-images.githubusercontent.com/7957590/59479005-6329d500-8e29-11e9-8049-5bd0f7d4aed4.jpg)

The biggest layout flap is the RHN header. It shifts all the stories down after the extension loads. I've misclicked on a story numerous times today because of this and it's extremely annoying. It also cannot be disabled.

Can we have an option to hide the RHN header and shouldn't these options be in the main extension options panel?

**Comment by chris-morgan** [comment]
A simple rough fix for the header:

```css
#pagespace + :not(.__rhn__options-bar) > td {
  padding-top: 31px;
}
```

As it stands this CSS is typically not loaded until just after the first draw, so there’s still *slight* layout flap, but it’s much less.

**Comment by nick-s-b** [comment]
@chris-morgan how about a way to just completely hide the RHN header?

**Comment by chris-morgan** [comment]
```css
.__rhn__options-bar {
  display: none;
}
```

**Comment by plibither8** [comment]
I'll give a more detailed response to all the conversation soon, but if you want to remove the options bar completely, just disable all the three features that depend on it:

* sort-stories
* hide-read-stories
* auto-refresh

**Comment by plibither8** [comment]
@chris-morgan @nick-s-b @Ajedi32 @cdtinney

How about adding an option in the popup to position the options bar at the bottom of the page instead of top? This way there won't be much of a visible layout flap too.

**Comment by nick-s-b** [comment]
@plibither8 that would be a lot better position since it wouldn't cause the page to shift. great idea!

**Comment by plibither8** [comment]
Commits https://github.com/plibither8/refined-hacker-news/commit/c8f10c6a7c0a1a88565e68e2a9c2525f8346a49e and https://github.com/plibither8/refined-hacker-news/commit/9da1fa579f2d5b77808c1dda00c38f4e1ebeffac fix the two major issue points that have been discussed in this thread.

I will close the issue soon if no one objects.

**Comment by plibither8** [comment]
Since there are no objections, I'm closing this issue.
