### ISSUE TITLE
Clicks should only be intercepted if unmodified

### ISSUE THREAD

**Issue by chris-morgan** [plibither8/refined-hacker-news#26]
Take the “reply” link as an example. (There may be others, but I know this one.) If I didn’t use the left mouse button, or if I am holding down a modifier key, it should let the browser do its thing rather than showing the form inline. Ctrl-click, Cmd-click and middle-click, for example, will most likely open the link in a new tab.

This is the function we use at FastMail:

```javascript
function isClickModified(event) {
    return !!event.button ||
        event.altKey || event.ctrlKey || event.metaKey || event.shiftKey;
}
```

… then almost all click handlers start with “`if (isClickModified(event)) { return; }`”.

**Comment by plibither8** [comment]
Again, great suggestion! I'll implement this in the next few updates of the extension :)
