### ISSUE TITLE
Safari?

### ISSUE THREAD

**Issue by sted** [plibither8/refined-hacker-news#31]

**Comment by plibither8** [comment]
Hi!

I won't be supporting Safari extension development. As mention in one of the Hacker News comments:

> Safari has traditionally used a different extension API, which coupled with this smaller adoption has hindered the progress of extensions in the platform. A recent change to an app extension model has hurt the ecosystem even more, as it killed a significant portion of the already few extensions that used to exist.

and

> Safari uses its own Safari Extensions JS, so while it may be possible to share some resources (e.g. images, HTML content), the js work needs to be undertaken as a separate development project, unless you use/build a polyfill.

Cheers!

**Comment by nesl247** [comment]
Is there any plan to reconsider now that Safari supports the Web Extensions API?

**Comment by plibither8** [comment]
Hey! I wasn't aware about this development. But unfortunately I don't have an Apple device to develop for Safari. If you can take this up I'll happily assign and review it :)
