### ISSUE TITLE
Add short explanation on permissions

### ISSUE THREAD

**Issue by skorokithakis** [plibither8/refined-hacker-news#33]
I saw the extension on HN and it looks great and I want to use it, but I'd like to know why it needs to access my browsing history. Will it send the data anywhere? Perhaps there could be an explanation in the README or the extension page.

**Comment by plibither8** [comment]
Persmission to access browsing history is required for the `hide-read-stories` feature. The feature needs to check whether the story has been visited in the past, ie, it's in your history.

No data whatsoever, including browsing history, is sent anywhere by this extension. All data, whatever stored, is stored locally or synced to your Chrome account.

Thanks for the suggestion to explain the permissions on the README, I'll surely do that. Cheers!
