### ISSUE TITLE
Feature Request - Navigation Keymaps

### ISSUE THREAD

**Issue by VinceG3** [plibither8/refined-hacker-news#34]
Hi, I'd love to have keymaps in order to easily navigate to HN sections, for example alt-h for home and alt-t for threads, maybe alt-s for submit and alt-p for profile

**Comment by plibither8** [comment]
Hey, thanks for opening this issue and great suggestion! My only concern is that some of these keymaps might interfere with keymaps used by other extensions or by the browser itself.

**Comment by VinceG3** [comment]
You could always just use command-control mappings like you do for some of the other actions. I just suggested alt because one of the other projects I use for a different site does the same thing. One option might be to do what gmail does, use the 'g' key for go, then the key pressed after determines where you go. e.g. for gmail you can press 'g' then 'i' to go to your inbox. Or 'g' then 'd' to go to your drafts. 

I'm just going to remap them via my keyboard anyway.

**Comment by plibither8** [comment]
Yup, I thought so too.

I've already started working on the featured, going to be named `universal-key-bindings`. Is there a more appropriate name that comes to your mind?

**Comment by VinceG3** [comment]
`sitewide-key-bindings`?
