### ISSUE TITLE
Feature request: Linkify footnotes and markdown links

### ISSUE THREAD

**Issue by christopher-dG** [plibither8/refined-hacker-news#35]
Footnotes:

```
This [1] is a good website.
[1] https://github.com
```

Here it would be great to be able to click on the first `[1]` and be taken to github.com.

Markdown:

```
[This](https://github.com) is a good website.
```

Here it would be great to render a link the way it appears [here](https://github.com).

It might also be nice to just render all comments as Markdown, but that's a separate feature...

**Comment by plibither8** [comment]
Hi!

This feature won't be easy to implement and it certainly won't work always. The thing about these numbered-reference links is that there is no "one" way or "correct" way to type them, which leads to many many different variations. Many times the number `[1]` does not correspond to the word to its left either. So there are many different exceptions there too.

If you take a look at the keybindings for comments, when a comment with these reference links is highlighted and suppose it has something like this:

```
This [1] is a good website.
[1] https://github.com
```

Then you can press the <kbd>1</kbd> key on your keyboard and the link to github.com will be opened.

Thanks again, and cheers!
