### ISSUE TITLE
Bug: Profile Links Dropdown not working

### ISSUE THREAD

**Issue by andspenrob** [plibither8/refined-hacker-news#38]
A feature I really enjoy in HNES is that a logged-in user has a drop-down menu on-hover by their name in the upper-right, which lets you link to the various user pages that are available under the user ID link, including:

  | change password
  | submissions
  | comments
  | hidden
  | upvoted submissions / comments (private)
  | favorite submissions / comments (shared)

It makes it much easier to navigate previous conversations, etc. Great work on RHN!

**Comment by plibither8** [comment]
It's already there, the `profile-links-dropdown` feature does exactly what you want! :slightly_smiling:

Tell me if I've understood it incorrectly.

**Comment by plibither8** [comment]
Clarification: instead of hovering over the username, you have to click it to access the dropdown.

**Comment by andspenrob** [comment]
Glad you thought of this!

Hmm... This could be a bug with the Firefox Extension or some strange setting blocking the JS on my end...

Here are two screen-caps of a Console error and of a grayed out <div> when I inspect the down arrow button.



Any Ideas?

**Comment by plibither8** [comment]
I can't see the screencaps, would you mind sending them again?

**Comment by andspenrob** [comment]
Images didn't take... Here they are again.
![SourceMapError](https://user-images.githubusercontent.com/51801119/59546771-87002000-8ee8-11e9-9b0c-3e62ad516fda.jpg)
![GrayedOutDiv](https://user-images.githubusercontent.com/51801119/59546773-89fb1080-8ee8-11e9-994b-173884b3657f.jpg)

**Comment by andspenrob** [comment]
And this error seems to be a [Firefox bug](https://developer.mozilla.org/en-US/docs/Tools/Debugger/Source_map_errors?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default#NetworkError_when_attempting_to_fetch_resource)?

**Comment by plibither8** [comment]
I think the network error (which is in fact a warning only) that is appearing is irrelevant to the extension.

The div is probably greyed out because `display` is set to `none` on it right now. Try clicking your username instead of the arrow to access the dropdown.

**Comment by andspenrob** [comment]
When I click on the username, it just takes me to the standard HN page. I don't get a dropdown... :-(

**Comment by plibither8** [comment]
This is unfortunate :/

It might be a lot to ask, but could you record the screen and console while you click the dropdown? I couldn't get much from the screencaps

**Comment by plibither8** [comment]
My apologies! This is definitely a bug, I am facing it too!

Working on it right away.

**Comment by plibither8** [comment]
I'll be releasing the updated version of the extension soon!

**Comment by plibither8** [comment]
I have updated the Chrome and Firefox extensions from my end. The updates should be active soon. Thanks again for pointing this out! :)
