### ISSUE TITLE
“Features to disable” textbox loses keypresses if you type quickly

### ISSUE THREAD

**Issue by chris-morgan** [plibither8/refined-hacker-news#41]
My guess, without referring to code, is that there’s some sort of slow two-way data binding involved. If I type at even fifty words a minute it still loses the occasional keypress; at a hundred words a minute it loses quite a few.

**Comment by plibither8** [comment]
Yes, after looking into the problem deeper, I've realised that the 'OptionsSync' function causes this to happen. I think it's more appropriate to register this bug in the [webext-options-sync repo](https://github.com/bfred-it/webext-options-sync).

Thanks for pointing it out :)
