### ISSUE TITLE
Don't allow key-bindings when textarea is active

### ISSUE THREAD

**Issue by plibither8** [plibither8/refined-hacker-news#44]

**Comment by PierBover** [comment]
While writing a reply and pressing `f` it favorites the current parent.

There are other problems with this. I'm not sure which key binding it is, but the page got reloaded and my long comment got deleted.

**Comment by plibither8** [comment]
Yeah, I've faced the same issue. I'm currently working on the fix, expect an update anytime today. Thanks :)

**Comment by PierBover** [comment]
Awesome!

This is a great extension btw. Super useful!

**Comment by plibither8** [comment]
Thank you so much! :smile:

**Comment by PierBover** [comment]
Have you updated the Chrome web store?

I'm still getting issues with key bindings when writing comments.

**Comment by plibither8** [comment]
Hey,

Unfortunately, Chrome has put the latest version of the extension on hold and now it's "pending review" which is notoriously known to take almost a week to be successfully completed.

![screenshot](https://imgur.com/a/v38sjER) 

I had pushed the update 3 days back but I think we have to wait maybe 4 more days for this to complete.

I will update you as soon as the extension gets updated. Until then maybe you could disable the "key-bindings-on-items" feature.

Thanks so much for your patience, cheers :)

**Comment by PierBover** [comment]
No problem. Thanks for the update!

**Comment by plibither8** [comment]
The extension has been updated on the Chrome Webstore, thanks for your patience :)
