### ISSUE TITLE
Build issue: stylus: command not found

### ISSUE THREAD

**Issue by olfilato** [plibither8/refined-hacker-news#56]
Trying to build the repo on macOS. Ran `npm install` successfully. Afterwards, trying to run either `npm run build` or `npm run watch` gives the `stylus: command not found` error.

**Comment by plibither8** [comment]
Try `npm install -g stylus `

**Comment by olfilato** [comment]
Issue resolved, thanks! That should probably be mentioned in the contribution guide, however.

**Comment by plibither8** [comment]
Agreed, will do soon! Thanks :)
