### ISSUE TITLE
Bug: Ctrl opens 'undefined' page

### ISSUE THREAD

**Issue by hadrienbecle** [plibither8/refined-hacker-news#58]
On Firefox 60.8.0esr with version 19.7.27.1549 of the extension, when I click on the Ctrl button, I'm redirected to https://news.ycombinator.com/undefined.

If I disable `site-navigation-key-bindings.js` in the settings, the problem disappears.

**Comment by plibither8** [comment]
I have just pushed a fix for this and uploaded the latest, fixed version. Thank you so much bringing this to notice.

**Comment by hadrienbecle** [comment]
Wow that was fast! Thank you very much!
