### ISSUE TITLE
can't enter "i" in the reply box

### ISSUE THREAD

**Issue by Vixine** [plibither8/refined-hacker-news#59]
when ever I enter "i" or "I" in the reply textbox the page redirects to https://news.ycombinator.com/undefined

**Comment by plibither8** [comment]
Hi, I really apologize for this bug. This was introduced two commits back and I had pushed a fix for it, but Chrome Web Store did not allow me to roll the version back. I have recently pushed an update to the extension that fixes this issue and you shall soon receive it. Until then, please disable `site-navigation-key-bindings` function. Thank you so much for your patience!

**Comment by plibither8** [comment]
Hi! I'd like to tell you that the extension has successfully been updated on the Chrome Web Store. If you want you can manually update it too! Thanks!

**Comment by compuguy** [comment]
That did the trick @plibither8!

**Comment by PierBover** [comment]
I'm having a similar issue when I press `h` I go home.

Honestly all these keybinding should never be activated by default, specially when you are writing a comment...

**Comment by plibither8** [comment]
I'm apologize for that @PieBover. Ideally the feature had mapped Home for Alt+H but a incorrect, buggy version of the extension which I pushed had incorrect mappings. I pushed the fixed version yesterday, so please update to the latest version. Thanks a lot.

**Comment by PierBover** [comment]
No worries, thanks again for your work on this extension. It's super helpful!
