### ISSUE TITLE
Feature request: Open page in Internet Archive

### ISSUE THREAD

**Issue by cglong** [plibither8/refined-hacker-news#68]
Shamelessly stolen from [this HN comment](https://news.ycombinator.com/item?id=21766547). It'd be cool if there was a link that would open a link using [the Internet Archive](https://archive.org/); it could even include the submission time to automatically navigate to the closest snapshot 🙂

**Comment by plibither8** [comment]
Hi!

Sounds like a great idea. Got a few clarifications: as mentioned in the comment, should this link archive the webpage or should it we an archived version of the page?

**Comment by plibither8** [comment]
I'll probably go with the way savepagenow is handling it: https://github.com/pastpages/savepagenow/blob/master/savepagenow/api.py

**Comment by cglong** [comment]
Thanks 😄 I was thinking this link would allow you to navigate to an archived version of the page.

**Comment by plibither8** [comment]
Yup! If no archived version is found, it will archive it, otherwise return the cached/archived version. How does that sound?

**Comment by cglong** [comment]
That sounds great! 😄

**Comment by plibither8** [comment]
Hey @cglong, I've created the feature and pushed the updated versions to production on Chrome and Firefox. It's up and running on FF, and might take a bit more time to be live on the Chrome Webstore.

Cheers!
