### ISSUE TITLE
Feature request: open story comments in new tab

### ISSUE THREAD

**Issue by lookfirst** [plibither8/refined-hacker-news#70]
Similar to `open-story-links-in-new-tab`, but for the link to the comments.

**Comment by plibither8** [comment]
Do you want to click the "comments" link and then it opens in a new tab _with focus_, or when you have the item highlighted using keyboard controls, and then open it in a new tab?

**Comment by lookfirst** [comment]
Does not need focus.

My workflow is to go down the front page and click on all the links that are interesting and open new tabs. When I have time, I go through the tabs and read/close them out. For links I care about the comments, I also open those.

**Comment by plibither8** [comment]
Alright got it. How about this: in the popup menu, I add an option which when enabled, performs the action?

**Comment by lookfirst** [comment]
Default off is fine with me.

**Comment by lookfirst** [comment]
@plibither8 THANK YOU!  Much happiness!

**Comment by plibither8** [comment]
Hey, no problem! I've _just_ published it on Mozilla Add-ons. The Chrome Webstore update might take some time because they have increased their review time.

**Comment by lookfirst** [comment]
Stay safe man! =)

**Comment by plibither8** [comment]
You too! :D
