### ISSUE TITLE
Firefox: Source map error when attempting to apply dark mode.

### ISSUE THREAD

**Issue by Forbo** [plibither8/refined-hacker-news#86]
The dark mode CSS doesn't appear to apply correctly in Firefox on Ubuntu. I find the following in my browser's console:

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://554fa046-0d16-4e9d-a042-728ebf840c93/browser-polyfill.min.js
Source Map URL: browser-polyfill.min.js.map

Previously referenced in another issue here: https://github.com/plibither8/refined-hacker-news/issues/84#issuecomment-740843529

**Comment by plibither8** [comment]
Also just to note: I saw your comment on HN and the attached image - the Firefox version does seem to have a _lot_ of bugs especially in the popup. I'll have to properly investigate that soon. The non-buggy version should look like this:

![image](https://user-images.githubusercontent.com/31861755/101529481-9d404c80-39b6-11eb-9410-d1d455a7de8f.png)

**Comment by plibither8** [comment]
Source-map errors are behind-the-scene errors that don't cause any bugs to the user. This is pretty low priority, so I'll close this but keep a note of it. Thanks!
