### ISSUE TITLE
Unable to donate via PayPal.

### ISSUE THREAD

**Issue by Forbo** [plibither8/refined-hacker-news#87]
When attempting to send you a donation via PayPay, I get a message stating "Sorry, this recipient can’t accept payments right now."

Do you have a Bitcoin or Monero address I could send to, instead?

**Comment by plibither8** [comment]
Hi. Thank you very much for considering a donation.

My PayPal account has been temporarily inaccessible because of some changes.

I don't have a Bitcoin/Monero address. Alternately, you could donate through Buy Me A Coffee: https://www.buymeacoffee.com/plibither8 :)

**Comment by plibither8** [comment]
@Forbo forgot I do have a BTC wallet. Here's the address: 3F8GaV5zdJqQaij8eSxXCDc97cHgVzFxnD

**Comment by plibither8** [comment]
@Forbo just wondering if you were considering a donation, I don't mean to sound deperate though :sweat_smile:.

**Comment by Forbo** [comment]
I sent a tip via xmr.to, it looked like it was set to go through at the time. I'm checking up on it now to see if it did or not.

**Comment by plibither8** [comment]
Ahh alright, understood.

**Comment by plibither8** [comment]
@Forbo shall I close this? Since https://paypal.me/plibither8 is working now :)

**Comment by Forbo** [comment]
Looks like Bitcoin fees were probably too high at the time. Looks like Paypal is working, closing this out.

**Comment by plibither8** [comment]
Awesome, cheers!
