### ISSUE TITLE
[Bug?]Firefox Menu appears broken

### ISSUE THREAD

**Issue by diego898** [plibither8/refined-hacker-news#88]
The menu appears broken for me:

<img width="555" alt="image" src="https://user-images.githubusercontent.com/742407/104366385-ea946a00-54de-11eb-9057-38ca7b4ff5df.png">

**Comment by plibither8** [comment]
Hi @diego898, thanks for opening the issue :). #71 is open and discusses this bug, so I'll keep just that open. I haven't got time to update things on this repo due to work at my uni, I'll get back to it as soon as possible :).
